<a href="https://colab.research.google.com/github/IrfanKpm/machine-learning-diaries/blob/main/pyTorch/_001_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
print(torch.__version__)

2.4.1+cu121


**Introduction to Tensors**

***What is a Tensor?***

A tensor is a generalization of matrices to more dimensions. Tensors are a core data structure in PyTorch, and they can represent:

- Scalars (0-dimensional tensors)
- Vectors (1-dimensional tensors)
- Matrices (2-dimensional tensors)
- And higher-dimensional arrays (3D, 4D, etc.)

Tensors in PyTorch are similar to NumPy arrays, but with the added advantage of being able to run on GPUs, which makes them powerful for deep learning tasks.

In [ ]:
  # scalar tensor
s1 = torch.tensor(4)
s1

tensor(4)

In [ ]:
# Create a tensor from a list
tensor = torch.tensor([1, 2, 3, 4, 5])
print(tensor)  # Output: tensor([1, 2, 3, 4, 5])
print(tensor.dtype)  # Output: torch.int64 (by default it's int64)

tensor([1, 2, 3, 4, 5])
torch.int64


In [ ]:
print(tensor)
print(tensor.shape)
print(tensor.ndim)

tensor([1, 2, 3, 4, 5])
torch.Size([5])
1


In [ ]:
# Create a tensor with a specific data type
float_tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
print(float_tensor)  # Output: tensor([1., 2., 3.])
print(float_tensor.dtype)  # Output: torch.float32

tensor([1., 2., 3.])
torch.float32


In [ ]:
# Create a random tensor with a shape of 2 rows and 3 columns
random_tensor = torch.rand(2, 3)
print(random_tensor)

tensor([[0.8102, 0.6952, 0.0065],
        [0.5246, 0.5331, 0.8465]])


In [ ]:
# Create a random integer tensor with values between 0 and 10, shape of 2 rows and 3 columns
random_tensor = torch.randint(low=0, high=10, size=(2, 3), dtype=torch.int32)
print(random_tensor)

tensor([[0, 0, 3],
        [9, 7, 5]], dtype=torch.int32)


In [ ]:
# Tensor filled with zeros
zero_tensor = torch.zeros(3, 3)
# Tensor filled with ones
ones_tensor = torch.ones(2, 2)

print(zero_tensor)
print()
print(ones_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# Create a tensor with shape (2, 3)
r1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(r1) #print r1
# Check the shape of the r1
print("\n",r1.shape)  # Output: torch.Size([2, 3])
# Reshape the tensor to shape (3, 2)
reshaped_tensor = r1.view(3, 2)
print("\n",reshaped_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])

 torch.Size([2, 3])

 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
  # Normal Distribution
mean = 0.0
std = 1.0
random_tensor = torch.normal(mean=mean, std=std, size=(2, 3))
print(random_tensor)

tensor([[ 1.0300, -1.9355, -1.2437],
        [-0.3383,  0.3734, -1.0481]])


**Manipulating tensors (tensor operations)**

In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Create a random tensor t1 with integers between 10 and 19, shape (2, 3)
t1 = torch.randint(low=10, high=20, size=(2, 3))
# Create a random tensor t2 with integers between 0 and 9, shape (3, 2)
t2 = torch.randint(low=0, high=10, size=(3, 2))
print(t1)  # Print t1 tensor
print(t2)  # Print t2 tensor
# Perform matrix multiplication using the @ operator
print(t1 @ t2)

tensor([[12, 16, 17],
        [13, 18, 15]])
tensor([[1, 1],
        [0, 2],
        [9, 4]])
tensor([[165, 112],
        [148, 109]])


**Finding the min, max, mean, sum, etc (aggregation)**

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [ ]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))