<a href="https://colab.research.google.com/github/IrfanKpm/Machine-Learning-Notes1/blob/main/basics/Lnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lnumpy.ipynb

This notebook is designed to help you learn and understand the basics of NumPy, a fundamental package for scientific computing in Python.

## What is NumPy?
NumPy, short for Numerical Python, is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures efficiently.

## Uses of NumPy
1. **Array Creation**: NumPy provides an efficient way to create and manipulate arrays. It supports both single-dimensional (1D) and multi-dimensional (2D, 3D, etc.) arrays.

2. **Mathematical Operations**: You can perform element-wise operations, matrix operations, and linear algebra operations with NumPy. This includes addition, subtraction, multiplication, division, dot product, cross product, etc.

3. **Statistical Operations**: NumPy offers a variety of functions to compute statistical measures such as mean, median, standard deviation, variance, etc.

4. **Data Handling**: NumPy arrays are used for storing and manipulating large datasets. They provide a more efficient and convenient way to handle data compared to Python's built-in lists.

5. **Integration with Other Libraries**: NumPy serves as the foundation for many other scientific libraries in Python, such as SciPy (for scientific computing), Pandas (for data analysis), Matplotlib (for plotting), and Scikit-learn (for machine learning).

6. **Random Number Generation**: NumPy includes functions for generating random numbers, which are useful in simulations, statistical modeling, and more.

## Installation
You can install NumPy using pip: pip install numpy


In [1]:
# pip install numpy

In [2]:
import numpy as np

## 1D array

A 1D array, or one-dimensional array, is a linear data structure consisting of a single row or single column of elements. It can be created using NumPy's `np.array()` function with a list or tuple of values.

In [10]:
a = np.array([2, 5, 10])  # Create a NumPy array 'a' with elements [2, 5, 10]
print(a.dtype)  # Print the data type of the array 'a'
print(a.ndim)   # Print the number of dimensions of the array 'a'


int64
1


In [30]:
b = np.array([4.2 , 6.0])
print(f"array b : {b}")
print(f"dtype of b : {b.dtype}")
print("Changing dtype to complex...")
b.dtype = "complex"  # Change the data type of array 'b' to complex
print(f"dtype of b : {b}")

array b : [4.2 6. ]
dtype of b : float64
Changing dtype to complex...
dtype of b : [4.2+6.j]


##2D Array
A 2D array, or two-dimensional array, represents a matrix with rows and columns. It can be created using NumPy's np.array() function with a nested list or a 2D array initializer.

In [106]:
c = np.array([
    [3,5,7],
    [0,4,2]
])
print(c)
print(c.dtype)
print(c.ndim)
print(c.flatten()) # flatten

[[3 5 7]
 [0 4 2]]
int64
2
[3 5 7 0 4 2]


## 3D Array
A 3D array, or three-dimensional array, extends the concept of a matrix into three dimensions. It is often used to represent data with three axes, such as RGB color images or volumetric data.

In [12]:
d = np.array([
    [
     [3,2,0],
     [1,1,5]
    ],
    [
     [9,6,6],
     [4,7,9]
    ]
])
print(d)
print(d.dtype)
print(d.ndim)

[[[3 2 0]
  [1 1 5]]

 [[9 6 6]
  [4 7 9]]]
int64
3


##Zero Matrix
A zero matrix is a matrix where all elements are zeros.

In [31]:
z = np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

## Ones Matrix
An ones matrix is a matrix where all elements are ones.

In the context of NumPy, the function np.ones((a, b, c)) creates a multi-dimensional array (tensor) filled with ones. Here's what a, b, and c represent:

**a:** Specifies the number of elements in the first dimension (axis 0). This corresponds to the number of rows in a 2D array or the depth in higher-dimensional arrays.

**b:** Specifies the number of elements in the second dimension (axis 1). This represents the number of columns in a 2D array or the width in higher-dimensional arrays.

**c:** Specifies the number of elements in the third dimension (axis 2). This dimension is optional and represents the depth in a 3D array or the width in higher-dimensional arrays.

In [34]:
o = np.ones((4,3,3),dtype="int32")
o

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [35]:
filled_arr = np.full((3,2),12)  # to create an array filled with a specified value.
filled_arr

array([[12, 12],
       [12, 12],
       [12, 12]])

In [37]:
range_arr =  np.arange(0,11,2) # (start, stop, step)
range_arr

array([ 0,  2,  4,  6,  8, 10])

In [49]:
arr_linspace = np.linspace(1, 10, 10) ## Create an array of 10 values from 0 to 1 (inclusive)
print(arr_linspace)
arr_linspace2 = np.linspace(2,11,7)
print(arr_linspace2)

print(arr_linspace.shape)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 2.   3.5  5.   6.5  8.   9.5 11. ]
(10,)


**arr_linspace** is a 1-dimensional array with 10 elements, as indicated by (10,) when printing arr_linspace.shape.
The shape (10,) means it has 10 elements along the first axis (rows in a 2D context).

In [59]:
# reshape
re_arr = np.arange(0,100,5)
print(re_arr)
print("\n(5,4) --->")
print(re_arr.reshape((5,4)))
print("\n(2,2,5) --->")
print(re_arr.reshape((2,2,5)))

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]

(5,4) --->
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]
 [80 85 90 95]]

(2,2,5) --->
[[[ 0  5 10 15 20]
  [25 30 35 40 45]]

 [[50 55 60 65 70]
  [75 80 85 90 95]]]


## Matrix Arithmatics
arr_a = [4, 6, 9]

arr_b = [0, 4, 2]

In [66]:
arr_a = np.array([4, 6, 9])
arr_b = np.array([1, 3, 9])

In [69]:
result_addition = arr_a + arr_b
print("Element-wise Addition:")
print(result_addition)

result_subtraction = arr_a - arr_b
print("\nElement-wise Subtraction:")
print(result_subtraction)

result_multiplication = arr_a * arr_b
print("\nElement-wise Multiplication:")
print(result_multiplication)

result_division = arr_a / arr_b
print("\nElement-wise Division:")
print(result_division)

dot_product = np.dot(arr_a, arr_b)
print("\nDot Product of arr_a and arr_b:")
print(dot_product)

Element-wise Addition:
[ 5  9 18]

Element-wise Subtraction:
[3 3 0]

Element-wise Multiplication:
[ 4 18 81]

Element-wise Division:
[4. 2. 1.]

Dot Product of arr_a and arr_b:
103


In [77]:
print(f"arr_a : {arr_a}")

# Scalar Addition
scalar_addition = arr_a + 10
print(f"\nScalar Addition (+10) : {scalar_addition}")

# Scalar Multiplication
scalar_multiplication = arr_a * 5
print(f"\nScalar Multiplication (*5) : {scalar_multiplication}")

# Exponentiation
exponentiation = arr_a ** 2
print(f"\nExponentiation (**2) : {exponentiation}")



arr_a : [4 6 9]

Scalar Addition (+10) : [14 16 19]

Scalar Multiplication (*5) : [20 30 45]

Exponentiation (**2) : [16 36 81]


In [79]:
   # Trigonometric Functions
trig_arr = [0,90,180,360]

print(f"trig_arr : {trig_arr}")
sin_values = np.sin(trig_arr)
cos_values = np.cos(trig_arr)
tan_values = np.tan(trig_arr)

print("Trigonometric Functions:")
print(f"sin(trig_arr) : {sin_values}")
print(f"cos(trig_arr) : {cos_values}")
print(f"tan(trig_arr) : {tan_values}")

trig_arr : [0, 90, 180, 360]
Trigonometric Functions:
sin(trig_arr) : [ 0.          0.89399666 -0.80115264  0.95891572]
cos(trig_arr) : [ 1.         -0.44807362 -0.59846007 -0.28369109]
tan(trig_arr) : [ 0.         -1.99520041  1.33869021 -3.38014041]


In [82]:
arrr = np.array([5,2,6,1,0,4])
print(arrr > 3)

[ True False  True False False  True]


In [83]:
# to create random elements in a matrix
np.random.random((3,4))

array([[0.34394403, 0.62228353, 0.68425046, 0.60956964],
       [0.60136825, 0.18059471, 0.09986609, 0.8877118 ],
       [0.41980524, 0.36175353, 0.90683814, 0.78897571]])

ar_a**.min()** finds the smallest value in the array ar_a

ar_a**.max()** finds the largest value in the array ar_a

ar_a**.sum()** calculates the sum of all elements in the array ar_an

In [103]:
ar_a = np.array([2,6,9,3,4,1])
print(f"array : {ar_a}")
print(f"min value : {ar_a.min()}")
print(f"max value : {ar_a.max()}")
print(f"sum pf array : {ar_a.sum()}")
print("Index of minimum value:", np.argmin(ar_a))
print("Index of maximum value:", np.argmax(ar_a))

array : [2 6 9 3 4 1]
min value : 1
max value : 9
sum pf array : 25
Index of minimum value: 5
Index of maximum value: 2


In [104]:
arr = np.array([[1, 2], [3, 4]])
print("Array:", arr)
print("Standard deviation:", np.std(arr))  # Output: 1.118033988749895 (standard deviation of all elements)


Array: [[1 2]
 [3 4]]
Standard deviation: 1.118033988749895


In [105]:
arr = np.array([[1, 2], [3, 4]])
print("Array:", arr)
print("Median:", np.median(arr))  # Output: 2.5 (median of all elements)


Array: [[1 2]
 [3 4]]
Median: 2.5


**Understanding Axis in NumPy Arrays**

In NumPy, "axis" refers to the specific dimension of an array. Arrays can have one or more dimensions, and each dimension is represented by its corresponding axis. When performing operations like finding the minimum, maximum, sum, mean, etc., you can specify along which axis these operations should be applied.

Key Points:

**0-axis (rows):** When working with a 2-dimensional array (matrix), axis 0 refers to the rows. Operations along axis 0 will be applied row-wise.

**1-axis (columns):** In a 2-dimensional array, axis 1 refers to the columns. Operations along axis 1 will be applied column-wise.

**Higher dimensions:** For arrays with more than two dimensions, each axis is sequentially numbered starting from 0. Operations can be specified along any of these axes.

**Examples:**

Finding minimum along axis 0: np.min(array, axis=0) will return the minimum value for each column in a 2-dimensional array.

Finding sum along axis 1: np.sum(array, axis=1) will calculate the sum of values for each row in a 2-dimensional array.

In [91]:
ar_b = np.arange(12).reshape(3,4)
print(ar_b)
print(np.max(ar_b,axis=0))
print(np.sum(ar_b,axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
[ 6 22 38]


In [100]:
bb = np.array([9,16,4]) ## sqrt
np.sqrt(bb)

array([3., 4., 2.])

In [101]:
# Example matrices
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_B = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

# Addition of matrices
matrix_addition = matrix_A + matrix_B
print("Matrix Addition:")
print(matrix_addition)

# Subtraction of matrices
matrix_subtraction = matrix_A - matrix_B
print("\nMatrix Subtraction:")
print(matrix_subtraction)

# Element-wise product (Hadamard product) of matrices
elementwise_product = matrix_A * matrix_B
print("\nElement-wise Product:")
print(elementwise_product)

# Matrix product (dot product)
matrix_product = np.dot(matrix_A, matrix_B)
print("\nMatrix Product:")
print(matrix_product)

# Transpose of a matrix
matrix_A_transpose = np.transpose(matrix_A)
print("\nTranspose of Matrix A:")
print(matrix_A_transpose)

# Trace of a matrix
matrix_trace = np.trace(matrix_A)
print("\nTrace of Matrix A:")
print(matrix_trace)


Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Product:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Transpose of Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Trace of Matrix A:
15


In [108]:
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])


vertical_stack = np.vstack((arr1, arr2))
horizontal_stack = np.hstack((arr1, arr2))

print("\nVertical Stack:")
print(vertical_stack)
print("\nHorizontal Stack:")
print(horizontal_stack)


Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]
