<a href="https://colab.research.google.com/github/IrfanKpm/machine-learning-diaries/blob/main/basics/numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1. Create a numpy array of integers from 1 to 10.

In [3]:
a1 = np.arange(1,11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Generate a 3x3 matrix with values ranging from 0 to 8.

In [4]:
a2 = np.arange(0,9).reshape(3,3)
a2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create an array of 12 zeros , in 4*3

In [5]:
a3 = np.zeros(12).reshape(4,3)
a3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

4. Create an array of 12 ones.

In [7]:
a4 = np.ones(12).reshape(2,6)
a4

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

5. Create a 3x3 matrix with random integers between 0 and 10.

In [8]:
a5 = np.random.randint(0,10,size=(3,3))
a5

array([[8, 9, 7],
       [1, 3, 0],
       [8, 9, 3]])

6. Perform element-wise addition, subtraction, multiplication, and division on two arrays.

In [13]:
arr1 = np.array([6,3,8,0])
arr2 = np.array([8,1,5,5])

np.add(arr1, arr2), np.subtract(arr1, arr2), np.multiply(arr1, arr2), np.divide(arr1, arr2)

(array([14,  4, 13,  5]),
 array([-2,  2,  3, -5]),
 array([48,  3, 40,  0]),
 array([0.75, 3.  , 1.6 , 0.  ]))

7. Create a 4x4 identity matrix.

In [16]:
a7 = np.eye(4)
a7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

8. Create a 2D array and find its shape

In [17]:
a8 = np.array([[1,7,3,9],[9,4,0,2]])
print(a8.shape)

(2, 4)


9. Convert an integer array to float.

In [19]:
a9 = np.array([1, 2, 3])
a9.astype(float)
a9

array([1, 2, 3])

10. Reverse the elements of a numpy array.

In [25]:
a10 = np.array([1, 2, 3,4,5,6])
a10 = a10[::-1]
a10

array([6, 5, 4, 3, 2, 1])

11. Find the sum of elements in each row and each column of a 3x3 matrix.

In [30]:
a11 = np.random.randint(0,10,size=(3,3))
print(a11)
print()
print(a11.sum(axis=0))
print(a11.sum(axis=1))

[[6 4 6]
 [3 4 6]
 [2 2 8]]

[11 10 20]
[16 13 12]


12. Find unique elements in a numpy array

In [32]:
a12 = np.array([3,7,7,5,3,9])
np.unique(a12)

array([3, 5, 7, 9])

13. Use boolean indexing to filter elements greater than a specific value in an array.

In [34]:
a13 = np.array([6,3,8,7,0,13,5])
a13[a13>6]

array([ 8,  7, 13])

14. Create an array of 5 evenly spaced numbers between 0 and 1

In [35]:
a14 = np.linspace(0,1,5)
a14

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

15. Transpose a 3x3 matrix

In [37]:
a15 = np.random.randint(4,16,size=(3,3))
print(a15)
print()
print(a15.T)

[[12 11 13]
 [ 5  8  4]
 [ 4 12  7]]

[[12  5  4]
 [11  8 12]
 [13  4  7]]
