<a href="https://colab.research.google.com/github/IrfanKpm/Machine-Learning-Notes1/blob/main/TensorFlow/_001_%20Learn_TensorFlow_and_Deep_Learning_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# machine learning > data into numbers and find patterns in those numbers

In [2]:
import tensorflow as tf

tf.__version__

'2.17.0'

##**tf.constant()**

In [3]:
# 'scalar' is a TensorFlow constant with a single value (a scalar).
# The value of this constant is set to 4.
# A scalar in TensorFlow is a 0-dimensional tensor, meaning it has no axes.
scalar = tf.constant(4)

scalar  # This will output the scalar tensor with the value 4.


<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
vector = tf.constant([4,8])

vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 8], dtype=int32)>

In [ ]:
scalar.ndim

0

In [ ]:
# 'vector' is a TensorFlow constant that represents a 1-dimensional tensor (a vector).
# The value of this constant is set to the list [4, 8].
# A vector in TensorFlow is a 1-dimensional tensor, meaning it has a single axis with a specific length.
vector = tf.constant([4, 8])

vector  # This will output the vector tensor with values [4, 8].

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 8], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([
    [4,3,1],
    [1,0,6]
])

matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 3, 1],
       [1, 0, 6]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix2 = tf.constant([
    [2.0 , 3.6],
    [1.7 , 2.3]
])

print("\nmatrix2")
print(f"shape > {matrix2.shape}") # shape
print(f"dtype > {matrix2.dtype}") # dtype
print(f"ndim > {matrix2.ndim}\n") # dimension

matrix3 = tf.constant([
    [2. , 5.],
    [6. , 1.]
],dtype=tf.float16)  # specify the data type with dtype prameter

print("matrix3")
print(f"shape > {matrix3.shape}")
print(f"dtype > {matrix3.dtype}")
print(f"ndim > {matrix3.ndim}\n")


matrix2
shape > (2, 2)
dtype > <dtype: 'float32'>
ndim > 2

matrix3
shape > (2, 2)
dtype > <dtype: 'float16'>
ndim > 2



In [ ]:
tensor1 = tf.constant([
    [
        [0 , 1 , 2 , 3 , 4],
        [5 , 6 , 7 , 8 , 9]
    ],
    [
        [10 , 11 , 12 , 13 , 14],
        [15 , 16 , 17 , 18 , 19]
    ],
    [
        [20 , 21 , 22 , 23 , 24],
        [25 , 26 , 27 , 28 , 29]
    ]
])

<p align="center">
  <img src="https://www.tensorflow.org/static/guide/images/tensor/3-axis_numpy.png" alt="Numpy Axes" width="200"/>
  <img src="https://www.tensorflow.org/static/guide/images/tensor/3-axis_front.png" alt="Front Axes" width="200"/>
  <img src="https://www.tensorflow.org/static/guide/images/tensor/3-axis_block.png" alt="Block Axes" width="200"/>
</p>

In [ ]:
tensor1

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

In [ ]:
tensor1.shape

TensorShape([3, 2, 5])

In [ ]:
tensor1.ndim

3

In [ ]:
tensor1.numpy() # Converts the TensorFlow tensor 'tensor1' to a NumPy array.

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)

In [56]:
t1 = tf.constant([4, 2, 7, 6, 9, 8, 3])

# Compute min, max, mean, and sum
min_value = tf.reduce_min(t1)
max_value = tf.reduce_max(t1)
mean_value = tf.reduce_mean(t1)
sum_value = tf.reduce_sum(t1)
variance_value = tf.math.reduce_variance(tf.cast(t1, tf.float32))
std_deviation = tf.math.reduce_std(tf.cast(t1, tf.float32))

# Print the results
print(f"Minimum value: {min_value.numpy()}")
print(f"Maximum value: {max_value.numpy()}")
print(f"Mean value: {mean_value.numpy()}")
print(f"Sum of elements: {sum_value.numpy()}")
print(f"Variance: {variance_value.numpy()}")
print(f"Standard Deviation: {std_deviation.numpy()}")

Minimum value: 2
Maximum value: 9
Mean value: 5
Sum of elements: 39
Variance: 5.959183692932129
Standard Deviation: 2.4411439895629883


## **Tensor Arithmetic Operations**

In [ ]:
# Define two tensors
tensor1 = tf.constant([15, 9, 7, 2])
tensor2 = tf.constant([5, 6, 7, 8])

In [ ]:
# Element-wise addition
addition_result = tf.add(tensor1, tensor2)
print("Addition Result:", addition_result.numpy())

Addition Result: [20 15 14 10]


In [ ]:
# Element-wise subtraction
subtraction_result = tf.subtract(tensor1, tensor2)
print("Subtraction Result:", subtraction_result.numpy())

Subtraction Result: [10  3  0 -6]


In [ ]:
# Element-wise multiplication
multiplication_result = tf.multiply(tensor1, tensor2)
print("Multiplication Result:", multiplication_result.numpy())

Multiplication Result: [75 54 49 16]


In [ ]:
# Element-wise division
division_result = tf.divide(tensor1, tensor2)
print("Division Result:", division_result.numpy())

Division Result: [3.   1.5  1.   0.25]


In [ ]:
# Define two 2D tensors (matrices)
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Matrix multiplication
matrix_multiplication_result = tf.matmul(matrix1, matrix2)
print("Matrix Multiplication Result:\n", matrix_multiplication_result.numpy())

Matrix Multiplication Result:
 [[19 22]
 [43 50]]


In [88]:
v1 = tf.constant([3, 2, 4], dtype=tf.float32)
v2 = tf.constant([1, 4, 2], dtype=tf.float32)

# Dot Product
dot_product = tf.tensordot(v1, v2, axes=1)
print("Dot Product:", dot_product.numpy())

# Cross Product
cross_product = tf.linalg.cross(v1, v2)
print("Cross Product:", cross_product.numpy())

Dot Product: 19.0
Cross Product: [-12.  -2.  10.]


##**tf.Variable**

In [ ]:
v1 = tf.Variable([10,10])

v1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

# TensorFlow Variables vs Constants

## TensorFlow Variable

- **Definition**: `tf.Variable` creates a mutable tensor.
- **Initialization**: For example, `v1 = tf.Variable([10, 10])`.
- **Mutability**: The value of a `tf.Variable` can be updated during execution.
- **Use Case**: Useful for parameters in machine learning models that need to be adjusted during training.

## TensorFlow Constant

- **Definition**: `tf.constant` creates an immutable tensor.
- **Initialization**: For example, `constant = tf.constant([10, 10])`.
- **Immutability**: Once a constant is created, its value cannot be changed.
- **Use Case**: Generally used for fixed values that do not need to be updated.

## Summary

- **`tf.constant([10, 10])`**: Unchangeable (constant value, cannot be modified)
- **`tf.Variable([10, 10])`**: Changeable (variable value, can be updated)


In [ ]:
v1[1].assign(7)
v1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
v1.assign_add([0,3]) # # Add [0, 3] to the current value of v1

v1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

## **Different Types of Tensors**

## Random Tensor

In [53]:
tf.random.set_seed(42)
r1 = tf.random.uniform(shape=[2,3],minval=10,maxval=40,dtype=tf.int32)
print("Random Tensor:\n", r1.numpy())

Random Tensor:
 [[17 39 21]
 [16 32 24]]


In [69]:
r = tf.constant([[3,6],[6,9],[0,1]])
print(r.numpy())
print("----------")
print(tf.random.shuffle(r).numpy())

[[3 6]
 [6 9]
 [0 1]]
----------
[[0 1]
 [6 9]
 [3 6]]


In [60]:
r2 = tf.random.normal(shape=[1,10],mean=4,stddev=1)
print("Random Normal Tensor:\n", r2.numpy())

Random Normal Tensor:
 [[4.0092463 3.3379374 3.2589731 5.1985264 4.8636208 4.3925757 4.934575
  3.8398254 1.8949466 5.3769717]]


## Fill Tensor

In [ ]:
f1 = tf.fill(dims=[2,4],value=6)
print("Filled Tensor:\n", f1.numpy())

Filled Tensor:
 [[6 6 6 6]
 [6 6 6 6]]


## Identity Tensor

In [ ]:
i = tf.eye(4)
print("Identity Tensor:\n", i.numpy())

Identity Tensor:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [70]:
import numpy as np

arr = np.array([4,8,1,5])
tarr = tf.constant(arr)
tarr

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([4, 8, 1, 5])>

## **Math Functions**

## tf.math.abs

In [ ]:
t1 = tf.constant([ 6.3 , -4.2 , -1.8])

print(tf.abs(t1).numpy())

[6.3 4.2 1.8]


In [ ]:
t2 = tf.constant([[4-3j],[-8+6j]])  # complex numbers
print(tf.abs(t2).numpy())

[[ 5.]
 [10.]]


##tf.math.add_n

In [5]:
t1 = tf.constant([[2,4],[5,3]])
t2 = tf.constant([[3,6],[1,4]])

result = tf.math.add_n([t1, t2])
print(result.numpy())

[[ 5 10]
 [ 6  7]]


## tf.math.add

In [12]:
x = tf.constant([3,6,1,7])
a = tf.constant(1)

print(tf.add(x,a))

tf.Tensor([4 7 2 8], shape=(4,), dtype=int32)


## square

In [69]:
asq = tf.constant([1,2,3,4,5])
print(f"x   > {asq.numpy()}")
print(f"x^2 > {tf.square(asq).numpy()}")

x   > [1 2 3 4 5]
x^2 > [ 1  4  9 16 25]


## sqrt

In [73]:
asr = tf.constant([81, 49],dtype=tf.float32)
print(f"x^2   > {asr.numpy()}")
sqrt_values = tf.sqrt(asr)
print(f"x > {sqrt_values.numpy()}")

x^2   > [81. 49.]
x > [9. 7.]


## tf.math.angle

In [16]:
c1 = tf.constant([1 + 0j])
print(tf.math.angle(c1))

c2 = tf.constant([3 + 4j])
print(tf.math.angle(c2))

tf.Tensor([0.], shape=(1,), dtype=float64)
tf.Tensor([0.92729522], shape=(1,), dtype=float64)


## tf.math.argmax

In [23]:
t1 = tf.constant([4,2,12,8,10])
max = tf.math.argmax(t1)
print(t1[max])
min = tf.math.argmin(t1)
print(t1[min])

tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


## tf.math.exp

In [25]:
# y = e^x
x = tf.constant(2.0)
y = tf.math.exp(x)
y

<tf.Tensor: shape=(), dtype=float32, numpy=7.389056>

## tf.math.log

In [32]:
x = tf.constant(4, dtype=tf.float32)
y = tf.math.log(x)
y

<tf.Tensor: shape=(), dtype=float32, numpy=1.3862944>

## tf.math.sigmoid

In [41]:
x = tf.constant([-5 , 0 , 5],dtype=tf.float32)
y = tf.math.sigmoid(x)
y.numpy()

array([0.00669285, 0.5       , 0.9933072 ], dtype=float32)

## tensor attributes

## 1. Shape

- **Definition**: The shape of a tensor describes the number of elements along each axis. It is often represented as a tuple of integers.
- **Example**: For a 2D tensor like `[[3, 6], [6, 9], [0, 1]]`, the shape is `(3, 2)`, meaning 3 rows and 2 columns.

## 2. Rank

- **Definition**: The rank of a tensor refers to the number of dimensions or axes it has. It is an integer.
- **Example**: For the tensor `[[3, 6], [6, 9], [0, 1]]`, which has 2 dimensions (rows and columns), the rank is `2`.

## 3. Axis or Dimension

- **Definition**: An axis (or dimension) refers to a particular direction along which the tensor's shape is defined. Each axis corresponds to a dimension in the tensor's shape.
- **Example**: In a 2D tensor with shape `(3, 2)`, axis 0 represents the rows, and axis 1 represents the columns.

## 4. Size

- **Definition**: The size of a tensor is the total number of elements it contains. It is the product of the sizes of all its dimensions.
- **Example**: For a tensor with shape `(3, 2)`, the size is `3 * 2 = 6`.

## Summary with 4D Example

Given the 4D tensor with shape `[2, 3, 4, 5]`:

- **Shape**: `(2, 3, 4, 5)`
  - This represents a tensor with 2 blocks
  - Each block contains 3 matrices
  - Each matrix has 4 rows
  - Each row contains 5 elements
- **Rank**: `4` (4D tensor)
- **Axis or Dimension**:
  - Axis 0: Represents the blocks (2 blocks)
  - Axis 1: Represents the matrices in each block (3 matrices per block)
  - Axis 2: Represents the rows in each matrix (4 rows per matrix)
  - Axis 3: Represents the elements in each row (5 elements per row)
- **Size**: `2 * 3 * 4 * 5 = 120` (total number of elements)

In [72]:
rank_4 = tf.zeros(shape=[2,3,4,5])
rank_4.numpy()

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)

In [75]:
print(rank_4.shape)
print(rank_4.ndim)
print(tf.size(rank_4))

(2, 3, 4, 5)
4
tf.Tensor(120, shape=(), dtype=int32)


## tensor indexing

In [79]:
tf.random.set_seed(42)
r = tf.random.uniform(shape=[2,3,4,5],minval=100,maxval=600,dtype=tf.int32)
r.numpy()

array([[[[287, 389, 361, 386, 292],
         [384, 383, 543, 171, 591],
         [352, 140, 351, 281, 120],
         [108, 359, 332, 509, 299]],

        [[311, 512, 597, 394, 319],
         [201, 161, 445, 406, 115],
         [370, 152, 101, 223, 468],
         [465, 403, 350, 303, 388]],

        [[152, 438, 301, 219, 292],
         [454, 382, 579, 139, 436],
         [216, 120, 120, 145, 543],
         [477, 375, 249, 207, 506]]],


       [[[309, 578, 582, 336, 404],
         [319, 239, 295, 385, 418],
         [241, 529, 187, 311, 258],
         [483, 396, 389, 556, 591]],

        [[313, 518, 497, 337, 152],
         [547, 161, 146, 129, 106],
         [125, 319, 580, 413, 572],
         [385, 335, 226, 472, 519]],

        [[374, 205, 333, 195, 179],
         [377, 317, 463, 511, 589],
         [408, 159, 468, 453, 348],
         [394, 360, 310, 293, 252]]]], dtype=int32)

In [80]:
# Access the element at position [1, 2, 3, 4]
element = r[1, 2, 3, 4]
print("\nElement at position [1, 2, 3, 4]:")
print(element.numpy())


Element at position [1, 2, 3, 4]:
252


In [81]:
# Slice the tensor to get the first block
slice_block = r[0, :, :, :]
print("\nFirst block (all rows, columns, and elements):")
print(slice_block.numpy())


First block (all rows, columns, and elements):
[[[287 389 361 386 292]
  [384 383 543 171 591]
  [352 140 351 281 120]
  [108 359 332 509 299]]

 [[311 512 597 394 319]
  [201 161 445 406 115]
  [370 152 101 223 468]
  [465 403 350 303 388]]

 [[152 438 301 219 292]
  [454 382 579 139 436]
  [216 120 120 145 543]
  [477 375 249 207 506]]]


In [84]:
# Slice to get the first block, second matrix, all rows, and columns from index 2 to the end
r[0,1,:,2:].numpy()

array([[597, 394, 319],
       [445, 406, 115],
       [101, 223, 468],
       [350, 303, 388]], dtype=int32)

In [86]:
# Slice to get the second block, third matrix, rows from index 2 to the end, and all columns
r[1,2,2:,:].numpy()

array([[408, 159, 468, 453, 348],
       [394, 360, 310, 293, 252]], dtype=int32)

## matrix manipulation

In [41]:
import numpy as np

In [42]:
tf.random.set_seed(42)
s1 = tf.random.uniform(shape=[3, 8], minval=20, maxval=60, dtype=tf.int32)
s2 = tf.random.uniform(shape=[2,3, 8], minval=20, maxval=60, dtype=tf.int32)

In [43]:
tf_arr1 = s1.numpy() # shape 3*8
print(tf_arr1)

[[27 29 21 46 32 44 23 23]
 [31 51 32 20 51 41 20 48]
 [39 52 29 59 51 52 57 34]]


In [44]:
tf_arr2 = tf.random.shuffle(tf_arr1).numpy() # shuffle tf_arr1
print(tf_arr2)

[[39 52 29 59 51 52 57 34]
 [31 51 32 20 51 41 20 48]
 [27 29 21 46 32 44 23 23]]


In [45]:
print(tf_arr2.flatten()) # tf_arr2 flatten

[39 52 29 59 51 52 57 34 31 51 32 20 51 41 20 48 27 29 21 46 32 44 23 23]


In [46]:
      # STACK USING NUMPY

numpy_arr1 = np.array(tf_arr1)
numpy_arr2 = np.array(tf_arr2)

print("numpy_arr1")
print(numpy_arr1)
print("\nnumpy_arr2")
print(numpy_arr2)

    # Horizontal stacking
hstack_arr = np.hstack((numpy_arr1, numpy_arr2))
print("\nHorizontal stacking")
print(hstack_arr)

    # Vertical stacking
vstack_arr = np.vstack((numpy_arr1, numpy_arr2))
print("\nVertical stacking")
print(vstack_arr)


numpy_arr1
[[27 29 21 46 32 44 23 23]
 [31 51 32 20 51 41 20 48]
 [39 52 29 59 51 52 57 34]]

numpy_arr2
[[39 52 29 59 51 52 57 34]
 [31 51 32 20 51 41 20 48]
 [27 29 21 46 32 44 23 23]]

Horizontal stacking
[[27 29 21 46 32 44 23 23 39 52 29 59 51 52 57 34]
 [31 51 32 20 51 41 20 48 31 51 32 20 51 41 20 48]
 [39 52 29 59 51 52 57 34 27 29 21 46 32 44 23 23]]

Vertical stacking
[[27 29 21 46 32 44 23 23]
 [31 51 32 20 51 41 20 48]
 [39 52 29 59 51 52 57 34]
 [39 52 29 59 51 52 57 34]
 [31 51 32 20 51 41 20 48]
 [27 29 21 46 32 44 23 23]]


In [47]:
tf_arr1_reshape1 = tf.reshape(s1, [4, 6])
print(tf_arr1_reshape1.numpy()) # [ 4 * 6 ]

[[27 29 21 46 32 44]
 [23 23 31 51 32 20]
 [51 41 20 48 39 52]
 [29 59 51 52 57 34]]


In [48]:
tf_arr2 = s2.numpy()
print(tf_arr2)

[[[38 43 39 54 32 33 24 42]
  [26 24 41 23 26 20 49 49]
  [20 41 24 57 20 58 21 36]]

 [[22 34 49 59 44 48 22 21]
  [57 53 47 35 27 36 51 44]
  [23 55 35 29 44 58 33 51]]]


In [49]:
tf_arr2_reshape1 = tf.reshape(s2, [6, 8])
print(tf_arr2_reshape1 .numpy())

[[38 43 39 54 32 33 24 42]
 [26 24 41 23 26 20 49 49]
 [20 41 24 57 20 58 21 36]
 [22 34 49 59 44 48 22 21]
 [57 53 47 35 27 36 51 44]
 [23 55 35 29 44 58 33 51]]


In [51]:
    # transpose
er1 = tf.transpose(tf_arr2_reshape1).numpy()
print(er1)

[[38 26 20 22 57 23]
 [43 24 41 34 53 55]
 [39 41 24 49 47 35]
 [54 23 57 59 35 29]
 [32 26 20 44 27 44]
 [33 20 58 48 36 58]
 [24 49 21 22 51 33]
 [42 49 36 21 44 51]]


In [39]:
           # STACK USING TENSORFLOW

# Create two 2x3 tensors
tensor1 = tf.random.uniform(shape=[2, 3], minval=10, maxval=50, dtype=tf.int32)
tensor2 = tf.random.uniform(shape=[2, 3], minval=10, maxval=50, dtype=tf.int32)

# Print the original tensors
print("Tensor 1:")
print(tensor1.numpy())

print("\nTensor 2:")
print(tensor2.numpy())

# Horizontal stacking using concat (along axis 1)
hstack_tensor = tf.concat([tensor1, tensor2], axis=1)

# Vertical stacking using concat (along axis 0)
vstack_tensor = tf.concat([tensor1, tensor2], axis=0)

# Print the stacked tensors
print("\nHorizontal Stack (hstack) using concat:")
print(hstack_tensor.numpy())

print("\nVertical Stack (vstack) using concat:")
print(vstack_tensor.numpy())


Tensor 1:
[[26 27 24]
 [48 10 42]]

Tensor 2:
[[13 11 17]
 [44 41 47]]

Horizontal Stack (hstack) using concat:
[[26 27 24 13 11 17]
 [48 10 42 44 41 47]]

Vertical Stack (vstack) using concat:
[[26 27 24]
 [48 10 42]
 [13 11 17]
 [44 41 47]]


## Squeezing a tensor

In [64]:
sq1 = tf.random.uniform(shape=[1,1, 4, 5], minval=20, maxval=60, dtype=tf.int32).numpy()

print("Original Tensor (sq1):")
print(sq1)
print("\nShape:", sq1.shape)

Original Tensor (sq1):
[[[[23 21 27 54 51]
   [57 49 27 40 37]
   [59 21 23 56 22]
   [29 27 35 20 44]]]]

Shape: (1, 1, 4, 5)


In [65]:
sq1_squeezed = tf.squeeze(sq1)
print("Squeezed Tensor:")
print(sq1_squeezed)
print("Shape after squeeze:", sq1_squeezed.shape)

Squeezed Tensor:
tf.Tensor(
[[23 21 27 54 51]
 [57 49 27 40 37]
 [59 21 23 56 22]
 [29 27 35 20 44]], shape=(4, 5), dtype=int32)
Shape after squeeze: (4, 5)


## one-hot encoding tensor

In [67]:
colors = [0,1,2,3]  # red , green , blue , purple
tf.one_hot(colors,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>